### ISSUE TITLE
expose kernel selection for chroma scaling

### ISSUE THREAD

**Issue by NSQY** [Jaded-Encoding-Thaumaturgy/vs-preview#110]
default bicubic rings and can be quite noticeable

**Comment by NSQY** [comment]
Example code https://github.com/NSQY/vs-preview/commit/a5edd75ca468c38ed30c76d54e5ee33886fef273

**Comment by Setsugennoao** [comment]
Use vskernels

**Comment by Setsugennoao** [comment]
What's the use for this?

**Comment by NSQY** [comment]
> What's the use for this?

Ringing introduced by re-sampling subsampled formats may be erroneously conflated with ringing in the source, even when there is none. This will be more common after chroma reconstruction (DPIR). A non-ringing kernel should be added as an option when working with anime in particular.

https://slow.pics/c/lr8B9MpW
