### ISSUE TITLE
Seek point halves every time a script is reloaded when using an interlaced source with "time" timeline mode

### ISSUE THREAD

**Issue by adworacz** [Jaded-Encoding-Thaumaturgy/vs-preview#126]
The video shows an example - while in the "time" timeline mode, if I have an interlaced output in my script, and I switch to it, then if I switch to a non-interlaced output and reload the script, the seek point cuts down by half every time I reload the script.

The video shows what I mean - the only thing I'm doing is reloading my script, and you can see the frame number dropping by half every reload.

https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/assets/561689/e0d2bece-122c-4e1c-9a51-a13c5e9da55b

**Comment by adworacz** [comment]
To be clear, I'm not sure if the issue is really deinterlaced clips, but at the very least clips with different frame numbers (like my interlaced vs deinterlaced outputs, with the deinterlaced output being twice the FPS of my interlaced output).

**Comment by wiwaz** [comment]
Could you provide a repro sample?

**Comment by adworacz** [comment]
Apologies. Yes I can provide a repro example, it will just take me a bit as I’m away from my main rig

**Comment by Setsugennoao** [comment]
Stale and can't repro, feel free to comment with a sample and will be reopened.

**Comment by adworacz** [comment]
Okay,I’ll try and find time to reproduce this soon.
