### ISSUE TITLE
Split planes doesn't account for negative values in chroma when in float

### ISSUE THREAD

**Issue by srappan** [Jaded-Encoding-Thaumaturgy/vs-preview#132]
Split Planes can't display chroma for clips in float properly.

![python_jTEUl3XVAp](https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/assets/26847675/8833c304-ee0e-4448-8773-68b29cebb801)
![python_ShSzU1tpGx](https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/assets/26847675/27f3b293-a96b-42eb-a167-2508abb06a6e)
![python_6lULtoPjTO](https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/assets/26847675/921b3be4-f8ad-419d-8e7f-90d09c324da8)
`delowpass` node is at a bit depth of 32
`CR`, `JPBD` nodes are at bit depth of 16

**Comment by Setsugennoao** [comment]
Check your monitor gamma

**Comment by NSQY** [comment]
The easiest fix for this would to simply ``x 0.5 +`` if the input is YUV type float. The plugin will also throw an error for half precision formats because ``vapoursynth.Error: Text: Input clip must be 8..16 bit integer or 32 bit float, passed GrayH.``

**Comment by Setsugennoao** [comment]
https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/commit/3bba1af229cce7578bfececef15f70ddf4fc0af1
