### ISSUE TITLE
Warn user if colourspace has to be assumed

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/vs-preview#139]
If any of the colourspace options (matrix/transfer/primaries) are set to 2, vspreview should warn the user that it has to assume the colourspace. This should imo display an error messages as such:

For example, 720x480 video:

```
WARN: The colorspace is unknown (2/2/2)! Assuming 6/6/6!
```

There are probably better ways to phrase this, but I want to get the following ideas across:

- The colourspace as it's currently tagged (in case i.e. matrix is tagged, but nothing else is)
- What it's assuming them to be right now.

As an extension, this should maybe also be included in `vstools.initialize_clip`, if only for transparency's sake. Maybe even make it a part of the function that tries to guess a colourspace based on heuristics (behind a `strict` param)?

**Comment by Setsugennoao** [comment]
I don't like the idea of logging that.
What about integrating it in the props tab.

**Comment by wiwaz** [comment]
+1 for warning
