### ISSUE TITLE
New button to enable SAR scaling

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/vs-preview#156]
It may be a nice feature to have a button in the Misc menu that enables SAR scaling. What this would do is use the kernel chosen in the settings window for resampling and use that same kernel to stretch the output image following the SAR props. Mostly useful to give you a better idea of what the video will look like at the display resolution.

**Comment by Setsugennoao** [comment]
Fixed in #166
