### ISSUE TITLE
Scening tool still broken

### ISSUE THREAD

**Issue by BReza27** [Jaded-Encoding-Thaumaturgy/vs-preview#171]
The scening tool is broken and will crash when doing several things. 

- [ ] Adding more than one section to a list
- [ ] Changing lists and trying to add a section
- [ ] Renaming a list

While modifying the toolbar it would be very nice if we could have an implementation for keyframes/scenechanges similar to wobbly. Currently they can be loaded in as their own list, but if they could be loaded in separately and skipped between or edited while being able to add those sections on another list that would be great. 

Error message:
  File "C:\Users\Reza\AppData\Roaming\Python\Python312\site-packages\vspreview\toolbars\scening\toolbar.py", line 336, in on_add_to_list_clicked
    self.current_list.add(self.first_frame, self.second_frame, self.label_lineedit.text())  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'add'

**Comment by Setsugennoao** [comment]
Was already fixed in https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/commit/41d8cc973bbed2e61c2dcecc00aa6eee37cfe9b3
