### ISSUE TITLE
Old msvc runtime loaded by pyqt6

### ISSUE THREAD

**Issue by myrsloik** [Jaded-Encoding-Thaumaturgy/vs-preview#190]
If pyqt6 loads before vapoursynth its own old bundled version of the visual studio runtime is loaded. This version is too old to work with vapoursynth which uses the most recent msvc and will immediately crash.

Putting `import vapoursynth` as the first line of `__init__.py` is an ugly hack that also fixes it.

**Comment by LightArrowsEXE** [comment]
Fixed in #191

**Comment by Real163** [comment]
bro i have python 3.12 but it wont install
